# This file is optional. It's only needed if you want to use Qdrant for
# persistent storage instead of the default in-memory vector store.
version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
